export { IFilter } from './filter.interface';
export { ICharacteristic } from './characteristic.interface';
export { ICoordinates } from './coordinates.interface';
export { IDay } from './day.interface';
export { ISchedule } from './schedule.interface';
export { IResponseData } from './response-data.interface';
export { IUserRegisterInfo } from './user-register-info.interface';
export { IUserLoginInfo } from './user-login-info.interface';
export { IPayload } from './payload-interface';