name: Frontend CI

on:
  push:
    branches: [ "task/*", "bugfix/*", "conf/*"]
  pull_request:
    branches: [ "master", "develop", "release/*", "feature/*" ]

jobs:
  start-on-ubuntu:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./price-map
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Start lint:front
        run: npm run lint
      - name: Start test
        run: npm run test:front
      - name: Start build
        run: npm run build:front
