name: OSRM Requester CI

on:
  workflow_dispatch:
  push:
    branches: [ "task/*", "bugfix/*", "conf/*", "feature/*" ]
  pull_request:
    branches: [ "master", "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./price-map
    strategy:
      matrix:
        node-version: [14.x, 16.x]
      
    steps:
    - name: Get repository code
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Start lint
      run: npm run lint:osrm-requester

  build:
    # needs: [lint]
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./price-map
    strategy:
      matrix:
        node-version: [14.x, 16.x]
      
    steps:
    - name: Get repository code
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Start build
      run: npm run execute:osrm-requester
