name: Overpass Requester CI

on:
  workflow_dispatch:
  push:
    branches: [ "task/*", "bugfix/*", "conf/*", "feature/*" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./price-map
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - name: Get repository code
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Install dependencies
      run: npm ci
    - name: Start build
      run: npm run build:overpass-requester