name: Scraper CI

on:
  workflow_dispatch:
  push:
    branches: [ "task/*", "bugfix/*", "conf/*", "feature/*" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./price-map
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Get repository code
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Move to folder
      run: cd apps/scraper/scraper
    - name: Install poetry dependencies
      run: poetry install
    - name: Run tests
      run: poetry run python test.py